/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPortalsRouteImport } from './routes/_authenticated/portals'
import { Route as AuthenticatedMessengerRouteImport } from './routes/_authenticated/messenger'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library.index'
import { Route as AuthenticatedBuyCoinsIndexRouteImport } from './routes/_authenticated/buy-coins.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedLibrarySongIdRouteImport } from './routes/_authenticated/library.$songId'
import { Route as AuthenticatedBuyCoinsReturnRouteImport } from './routes/_authenticated/buy-coins.return'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUserSettingsRouteImport } from './routes/_authenticated/admin.user-settings'
import { Route as AuthenticatedAdminOgPersonaRouteImport } from './routes/_authenticated/admin.og-persona'
import { Route as AuthenticatedAdminOgBotRouteImport } from './routes/_authenticated/admin.og-bot'
import { Route as AuthenticatedAdminCreatePortalRouteImport } from './routes/_authenticated/admin.create-portal'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalsRoute = AuthenticatedPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessengerRoute = AuthenticatedMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyCoinsIndexRoute =
  AuthenticatedBuyCoinsIndexRouteImport.update({
    id: '/buy-coins/',
    path: '/buy-coins/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibrarySongIdRoute =
  AuthenticatedLibrarySongIdRouteImport.update({
    id: '/library/$songId',
    path: '/library/$songId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyCoinsReturnRoute =
  AuthenticatedBuyCoinsReturnRouteImport.update({
    id: '/buy-coins/return',
    path: '/buy-coins/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUserSettingsRoute =
  AuthenticatedAdminUserSettingsRouteImport.update({
    id: '/admin/user-settings',
    path: '/admin/user-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOgPersonaRoute =
  AuthenticatedAdminOgPersonaRouteImport.update({
    id: '/admin/og-persona',
    path: '/admin/og-persona',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOgBotRoute = AuthenticatedAdminOgBotRouteImport.update({
  id: '/admin/og-bot',
  path: '/admin/og-bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCreatePortalRoute =
  AuthenticatedAdminCreatePortalRouteImport.update({
    id: '/admin/create-portal',
    path: '/admin/create-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/admin/create-portal': typeof AuthenticatedAdminCreatePortalRoute
  '/admin/og-bot': typeof AuthenticatedAdminOgBotRoute
  '/admin/og-persona': typeof AuthenticatedAdminOgPersonaRoute
  '/admin/user-settings': typeof AuthenticatedAdminUserSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/buy-coins/return': typeof AuthenticatedBuyCoinsReturnRoute
  '/library/$songId': typeof AuthenticatedLibrarySongIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/buy-coins/': typeof AuthenticatedBuyCoinsIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/create-portal': typeof AuthenticatedAdminCreatePortalRoute
  '/admin/og-bot': typeof AuthenticatedAdminOgBotRoute
  '/admin/og-persona': typeof AuthenticatedAdminOgPersonaRoute
  '/admin/user-settings': typeof AuthenticatedAdminUserSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/buy-coins/return': typeof AuthenticatedBuyCoinsReturnRoute
  '/library/$songId': typeof AuthenticatedLibrarySongIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/buy-coins': typeof AuthenticatedBuyCoinsIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/messenger': typeof AuthenticatedMessengerRoute
  '/_authenticated/portals': typeof AuthenticatedPortalsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/create-portal': typeof AuthenticatedAdminCreatePortalRoute
  '/_authenticated/admin/og-bot': typeof AuthenticatedAdminOgBotRoute
  '/_authenticated/admin/og-persona': typeof AuthenticatedAdminOgPersonaRoute
  '/_authenticated/admin/user-settings': typeof AuthenticatedAdminUserSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/buy-coins/return': typeof AuthenticatedBuyCoinsReturnRoute
  '/_authenticated/library/$songId': typeof AuthenticatedLibrarySongIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/buy-coins/': typeof AuthenticatedBuyCoinsIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messenger'
    | '/portals'
    | '/settings'
    | '/portal/$slug'
    | '/admin/create-portal'
    | '/admin/og-bot'
    | '/admin/og-persona'
    | '/admin/user-settings'
    | '/admin/users'
    | '/buy-coins/return'
    | '/library/$songId'
    | '/admin/'
    | '/buy-coins/'
    | '/library/'
    | '/admin/users/$userId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/messenger'
    | '/portals'
    | '/settings'
    | '/portal/$slug'
    | '/'
    | '/admin/create-portal'
    | '/admin/og-bot'
    | '/admin/og-persona'
    | '/admin/user-settings'
    | '/admin/users'
    | '/buy-coins/return'
    | '/library/$songId'
    | '/admin'
    | '/buy-coins'
    | '/library'
    | '/admin/users/$userId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/messenger'
    | '/_authenticated/portals'
    | '/_authenticated/settings'
    | '/portal/$slug'
    | '/_authenticated/'
    | '/_authenticated/admin/create-portal'
    | '/_authenticated/admin/og-bot'
    | '/_authenticated/admin/og-persona'
    | '/_authenticated/admin/user-settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/buy-coins/return'
    | '/_authenticated/library/$songId'
    | '/_authenticated/admin/'
    | '/_authenticated/buy-coins/'
    | '/_authenticated/library/'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalSlugRoute: typeof PortalSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portals': {
      id: '/_authenticated/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof AuthenticatedPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messenger': {
      id: '/_authenticated/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AuthenticatedMessengerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-coins/': {
      id: '/_authenticated/buy-coins/'
      path: '/buy-coins'
      fullPath: '/buy-coins/'
      preLoaderRoute: typeof AuthenticatedBuyCoinsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$songId': {
      id: '/_authenticated/library/$songId'
      path: '/library/$songId'
      fullPath: '/library/$songId'
      preLoaderRoute: typeof AuthenticatedLibrarySongIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-coins/return': {
      id: '/_authenticated/buy-coins/return'
      path: '/buy-coins/return'
      fullPath: '/buy-coins/return'
      preLoaderRoute: typeof AuthenticatedBuyCoinsReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/user-settings': {
      id: '/_authenticated/admin/user-settings'
      path: '/admin/user-settings'
      fullPath: '/admin/user-settings'
      preLoaderRoute: typeof AuthenticatedAdminUserSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/og-persona': {
      id: '/_authenticated/admin/og-persona'
      path: '/admin/og-persona'
      fullPath: '/admin/og-persona'
      preLoaderRoute: typeof AuthenticatedAdminOgPersonaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/og-bot': {
      id: '/_authenticated/admin/og-bot'
      path: '/admin/og-bot'
      fullPath: '/admin/og-bot'
      preLoaderRoute: typeof AuthenticatedAdminOgBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/create-portal': {
      id: '/_authenticated/admin/create-portal'
      path: '/admin/create-portal'
      fullPath: '/admin/create-portal'
      preLoaderRoute: typeof AuthenticatedAdminCreatePortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessengerRoute: typeof AuthenticatedMessengerRoute
  AuthenticatedPortalsRoute: typeof AuthenticatedPortalsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminCreatePortalRoute: typeof AuthenticatedAdminCreatePortalRoute
  AuthenticatedAdminOgBotRoute: typeof AuthenticatedAdminOgBotRoute
  AuthenticatedAdminOgPersonaRoute: typeof AuthenticatedAdminOgPersonaRoute
  AuthenticatedAdminUserSettingsRoute: typeof AuthenticatedAdminUserSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedBuyCoinsReturnRoute: typeof AuthenticatedBuyCoinsReturnRoute
  AuthenticatedLibrarySongIdRoute: typeof AuthenticatedLibrarySongIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBuyCoinsIndexRoute: typeof AuthenticatedBuyCoinsIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessengerRoute: AuthenticatedMessengerRoute,
  AuthenticatedPortalsRoute: AuthenticatedPortalsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminCreatePortalRoute: AuthenticatedAdminCreatePortalRoute,
  AuthenticatedAdminOgBotRoute: AuthenticatedAdminOgBotRoute,
  AuthenticatedAdminOgPersonaRoute: AuthenticatedAdminOgPersonaRoute,
  AuthenticatedAdminUserSettingsRoute: AuthenticatedAdminUserSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedBuyCoinsReturnRoute: AuthenticatedBuyCoinsReturnRoute,
  AuthenticatedLibrarySongIdRoute: AuthenticatedLibrarySongIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBuyCoinsIndexRoute: AuthenticatedBuyCoinsIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalSlugRoute: PortalSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
