/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MPreviewRouteImport } from './routes/m-preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedPurchaseHistoryRouteImport } from './routes/_authenticated/purchase-history'
import { Route as AuthenticatedPortalsRouteImport } from './routes/_authenticated/portals'
import { Route as AuthenticatedMessengerRouteImport } from './routes/_authenticated/messenger'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedBuyCoinsIndexRouteImport } from './routes/_authenticated/buy-coins.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedLibrarySongIdRouteImport } from './routes/_authenticated/library.$songId'
import { Route as AuthenticatedBuyCoinsReturnRouteImport } from './routes/_authenticated/buy-coins.return'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminUsersProRouteImport } from './routes/_authenticated/admin.users-pro'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUserSettingsRouteImport } from './routes/_authenticated/admin.user-settings'
import { Route as AuthenticatedAdminStoreRouteImport } from './routes/_authenticated/admin.store'
import { Route as AuthenticatedAdminRouteMapRouteImport } from './routes/_authenticated/admin.route-map'
import { Route as AuthenticatedAdminReferralsAuditRouteImport } from './routes/_authenticated/admin.referrals-audit'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAdminOgPersonaRouteImport } from './routes/_authenticated/admin.og-persona'
import { Route as AuthenticatedAdminDebugContextRouteImport } from './routes/_authenticated/admin.debug-context'
import { Route as AuthenticatedAdminCoinAuditRouteImport } from './routes/_authenticated/admin.coin-audit'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin.api-keys'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'

const AuthenticatedLibraryIndexLazyRouteImport = createFileRoute(
  '/_authenticated/library/',
)()

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MPreviewRoute = MPreviewRouteImport.update({
  id: '/m-preview',
  path: '/m-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseHistoryRoute =
  AuthenticatedPurchaseHistoryRouteImport.update({
    id: '/purchase-history',
    path: '/purchase-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalsRoute = AuthenticatedPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessengerRoute = AuthenticatedMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLibraryIndexLazyRoute =
  AuthenticatedLibraryIndexLazyRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/library.index.lazy').then((d) => d.Route),
  )
const AuthenticatedBuyCoinsIndexRoute =
  AuthenticatedBuyCoinsIndexRouteImport.update({
    id: '/buy-coins/',
    path: '/buy-coins/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibrarySongIdRoute =
  AuthenticatedLibrarySongIdRouteImport.update({
    id: '/library/$songId',
    path: '/library/$songId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyCoinsReturnRoute =
  AuthenticatedBuyCoinsReturnRouteImport.update({
    id: '/buy-coins/return',
    path: '/buy-coins/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/admin/webhooks',
    path: '/admin/webhooks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersProRoute =
  AuthenticatedAdminUsersProRouteImport.update({
    id: '/admin/users-pro',
    path: '/admin/users-pro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUserSettingsRoute =
  AuthenticatedAdminUserSettingsRouteImport.update({
    id: '/admin/user-settings',
    path: '/admin/user-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoreRoute = AuthenticatedAdminStoreRouteImport.update({
  id: '/admin/store',
  path: '/admin/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteMapRoute =
  AuthenticatedAdminRouteMapRouteImport.update({
    id: '/admin/route-map',
    path: '/admin/route-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReferralsAuditRoute =
  AuthenticatedAdminReferralsAuditRouteImport.update({
    id: '/admin/referrals-audit',
    path: '/admin/referrals-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/admin/onboarding',
    path: '/admin/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOgPersonaRoute =
  AuthenticatedAdminOgPersonaRouteImport.update({
    id: '/admin/og-persona',
    path: '/admin/og-persona',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDebugContextRoute =
  AuthenticatedAdminDebugContextRouteImport.update({
    id: '/admin/debug-context',
    path: '/admin/debug-context',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoinAuditRoute =
  AuthenticatedAdminCoinAuditRouteImport.update({
    id: '/admin/coin-audit',
    path: '/admin/coin-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/admin/api-keys',
    path: '/admin/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/m-preview': typeof MPreviewRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/purchase-history': typeof AuthenticatedPurchaseHistoryRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/r/$code': typeof RCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/coin-audit': typeof AuthenticatedAdminCoinAuditRoute
  '/admin/debug-context': typeof AuthenticatedAdminDebugContextRoute
  '/admin/og-persona': typeof AuthenticatedAdminOgPersonaRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/referrals-audit': typeof AuthenticatedAdminReferralsAuditRoute
  '/admin/route-map': typeof AuthenticatedAdminRouteMapRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/admin/user-settings': typeof AuthenticatedAdminUserSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/users-pro': typeof AuthenticatedAdminUsersProRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/buy-coins/return': typeof AuthenticatedBuyCoinsReturnRoute
  '/library/$songId': typeof AuthenticatedLibrarySongIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/buy-coins/': typeof AuthenticatedBuyCoinsIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexLazyRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/m-preview': typeof MPreviewRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/purchase-history': typeof AuthenticatedPurchaseHistoryRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/r/$code': typeof RCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/coin-audit': typeof AuthenticatedAdminCoinAuditRoute
  '/admin/debug-context': typeof AuthenticatedAdminDebugContextRoute
  '/admin/og-persona': typeof AuthenticatedAdminOgPersonaRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/referrals-audit': typeof AuthenticatedAdminReferralsAuditRoute
  '/admin/route-map': typeof AuthenticatedAdminRouteMapRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/admin/user-settings': typeof AuthenticatedAdminUserSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/users-pro': typeof AuthenticatedAdminUsersProRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/buy-coins/return': typeof AuthenticatedBuyCoinsReturnRoute
  '/library/$songId': typeof AuthenticatedLibrarySongIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/buy-coins': typeof AuthenticatedBuyCoinsIndexRoute
  '/library': typeof AuthenticatedLibraryIndexLazyRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/m-preview': typeof MPreviewRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/messenger': typeof AuthenticatedMessengerRoute
  '/_authenticated/portals': typeof AuthenticatedPortalsRoute
  '/_authenticated/purchase-history': typeof AuthenticatedPurchaseHistoryRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/r/$code': typeof RCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/coin-audit': typeof AuthenticatedAdminCoinAuditRoute
  '/_authenticated/admin/debug-context': typeof AuthenticatedAdminDebugContextRoute
  '/_authenticated/admin/og-persona': typeof AuthenticatedAdminOgPersonaRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/referrals-audit': typeof AuthenticatedAdminReferralsAuditRoute
  '/_authenticated/admin/route-map': typeof AuthenticatedAdminRouteMapRoute
  '/_authenticated/admin/store': typeof AuthenticatedAdminStoreRoute
  '/_authenticated/admin/user-settings': typeof AuthenticatedAdminUserSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/admin/users-pro': typeof AuthenticatedAdminUsersProRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/buy-coins/return': typeof AuthenticatedBuyCoinsReturnRoute
  '/_authenticated/library/$songId': typeof AuthenticatedLibrarySongIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/buy-coins/': typeof AuthenticatedBuyCoinsIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexLazyRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/m-preview'
    | '/mcp'
    | '/reset-password'
    | '/trust'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/change-password'
    | '/community'
    | '/developer'
    | '/messenger'
    | '/portals'
    | '/purchase-history'
    | '/referrals'
    | '/settings'
    | '/store'
    | '/portal/$slug'
    | '/r/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/api-keys'
    | '/admin/coin-audit'
    | '/admin/debug-context'
    | '/admin/og-persona'
    | '/admin/onboarding'
    | '/admin/referrals-audit'
    | '/admin/route-map'
    | '/admin/store'
    | '/admin/user-settings'
    | '/admin/users'
    | '/admin/users-pro'
    | '/admin/webhooks'
    | '/buy-coins/return'
    | '/library/$songId'
    | '/admin/'
    | '/buy-coins/'
    | '/library/'
    | '/admin/users/$userId'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/m-preview'
    | '/mcp'
    | '/reset-password'
    | '/trust'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/change-password'
    | '/community'
    | '/developer'
    | '/messenger'
    | '/portals'
    | '/purchase-history'
    | '/referrals'
    | '/settings'
    | '/store'
    | '/portal/$slug'
    | '/r/$code'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/api-keys'
    | '/admin/coin-audit'
    | '/admin/debug-context'
    | '/admin/og-persona'
    | '/admin/onboarding'
    | '/admin/referrals-audit'
    | '/admin/route-map'
    | '/admin/store'
    | '/admin/user-settings'
    | '/admin/users'
    | '/admin/users-pro'
    | '/admin/webhooks'
    | '/buy-coins/return'
    | '/library/$songId'
    | '/admin'
    | '/buy-coins'
    | '/library'
    | '/admin/users/$userId'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/m-preview'
    | '/mcp'
    | '/reset-password'
    | '/trust'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/change-password'
    | '/_authenticated/community'
    | '/_authenticated/developer'
    | '/_authenticated/messenger'
    | '/_authenticated/portals'
    | '/_authenticated/purchase-history'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/portal/$slug'
    | '/r/$code'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/coin-audit'
    | '/_authenticated/admin/debug-context'
    | '/_authenticated/admin/og-persona'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/referrals-audit'
    | '/_authenticated/admin/route-map'
    | '/_authenticated/admin/store'
    | '/_authenticated/admin/user-settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/users-pro'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/buy-coins/return'
    | '/_authenticated/library/$songId'
    | '/_authenticated/admin/'
    | '/_authenticated/buy-coins/'
    | '/_authenticated/library/'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MPreviewRoute: typeof MPreviewRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrustRoute: typeof TrustRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PortalSlugRoute: typeof PortalSlugRoute
  RCodeRoute: typeof RCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m-preview': {
      id: '/m-preview'
      path: '/m-preview'
      fullPath: '/m-preview'
      preLoaderRoute: typeof MPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-history': {
      id: '/_authenticated/purchase-history'
      path: '/purchase-history'
      fullPath: '/purchase-history'
      preLoaderRoute: typeof AuthenticatedPurchaseHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portals': {
      id: '/_authenticated/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof AuthenticatedPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messenger': {
      id: '/_authenticated/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AuthenticatedMessengerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-coins/': {
      id: '/_authenticated/buy-coins/'
      path: '/buy-coins'
      fullPath: '/buy-coins/'
      preLoaderRoute: typeof AuthenticatedBuyCoinsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$songId': {
      id: '/_authenticated/library/$songId'
      path: '/library/$songId'
      fullPath: '/library/$songId'
      preLoaderRoute: typeof AuthenticatedLibrarySongIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-coins/return': {
      id: '/_authenticated/buy-coins/return'
      path: '/buy-coins/return'
      fullPath: '/buy-coins/return'
      preLoaderRoute: typeof AuthenticatedBuyCoinsReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users-pro': {
      id: '/_authenticated/admin/users-pro'
      path: '/admin/users-pro'
      fullPath: '/admin/users-pro'
      preLoaderRoute: typeof AuthenticatedAdminUsersProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/user-settings': {
      id: '/_authenticated/admin/user-settings'
      path: '/admin/user-settings'
      fullPath: '/admin/user-settings'
      preLoaderRoute: typeof AuthenticatedAdminUserSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/store': {
      id: '/_authenticated/admin/store'
      path: '/admin/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AuthenticatedAdminStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/route-map': {
      id: '/_authenticated/admin/route-map'
      path: '/admin/route-map'
      fullPath: '/admin/route-map'
      preLoaderRoute: typeof AuthenticatedAdminRouteMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/referrals-audit': {
      id: '/_authenticated/admin/referrals-audit'
      path: '/admin/referrals-audit'
      fullPath: '/admin/referrals-audit'
      preLoaderRoute: typeof AuthenticatedAdminReferralsAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/og-persona': {
      id: '/_authenticated/admin/og-persona'
      path: '/admin/og-persona'
      fullPath: '/admin/og-persona'
      preLoaderRoute: typeof AuthenticatedAdminOgPersonaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/debug-context': {
      id: '/_authenticated/admin/debug-context'
      path: '/admin/debug-context'
      fullPath: '/admin/debug-context'
      preLoaderRoute: typeof AuthenticatedAdminDebugContextRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coin-audit': {
      id: '/_authenticated/admin/coin-audit'
      path: '/admin/coin-audit'
      fullPath: '/admin/coin-audit'
      preLoaderRoute: typeof AuthenticatedAdminCoinAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedMessengerRoute: typeof AuthenticatedMessengerRoute
  AuthenticatedPortalsRoute: typeof AuthenticatedPortalsRoute
  AuthenticatedPurchaseHistoryRoute: typeof AuthenticatedPurchaseHistoryRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminCoinAuditRoute: typeof AuthenticatedAdminCoinAuditRoute
  AuthenticatedAdminDebugContextRoute: typeof AuthenticatedAdminDebugContextRoute
  AuthenticatedAdminOgPersonaRoute: typeof AuthenticatedAdminOgPersonaRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminReferralsAuditRoute: typeof AuthenticatedAdminReferralsAuditRoute
  AuthenticatedAdminRouteMapRoute: typeof AuthenticatedAdminRouteMapRoute
  AuthenticatedAdminStoreRoute: typeof AuthenticatedAdminStoreRoute
  AuthenticatedAdminUserSettingsRoute: typeof AuthenticatedAdminUserSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminUsersProRoute: typeof AuthenticatedAdminUsersProRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedBuyCoinsReturnRoute: typeof AuthenticatedBuyCoinsReturnRoute
  AuthenticatedLibrarySongIdRoute: typeof AuthenticatedLibrarySongIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBuyCoinsIndexRoute: typeof AuthenticatedBuyCoinsIndexRoute
  AuthenticatedLibraryIndexLazyRoute: typeof AuthenticatedLibraryIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedMessengerRoute: AuthenticatedMessengerRoute,
  AuthenticatedPortalsRoute: AuthenticatedPortalsRoute,
  AuthenticatedPurchaseHistoryRoute: AuthenticatedPurchaseHistoryRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminCoinAuditRoute: AuthenticatedAdminCoinAuditRoute,
  AuthenticatedAdminDebugContextRoute: AuthenticatedAdminDebugContextRoute,
  AuthenticatedAdminOgPersonaRoute: AuthenticatedAdminOgPersonaRoute,
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminReferralsAuditRoute: AuthenticatedAdminReferralsAuditRoute,
  AuthenticatedAdminRouteMapRoute: AuthenticatedAdminRouteMapRoute,
  AuthenticatedAdminStoreRoute: AuthenticatedAdminStoreRoute,
  AuthenticatedAdminUserSettingsRoute: AuthenticatedAdminUserSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminUsersProRoute: AuthenticatedAdminUsersProRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedBuyCoinsReturnRoute: AuthenticatedBuyCoinsReturnRoute,
  AuthenticatedLibrarySongIdRoute: AuthenticatedLibrarySongIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBuyCoinsIndexRoute: AuthenticatedBuyCoinsIndexRoute,
  AuthenticatedLibraryIndexLazyRoute: AuthenticatedLibraryIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MPreviewRoute: MPreviewRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrustRoute: TrustRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PortalSlugRoute: PortalSlugRoute,
  RCodeRoute: RCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
